export const categories = [
  'Ação',
  'Aventura',
  'Comédia',
  'Drama',
  'Fantasia',
  'Ficção Científica',
  'Terror',
  'Romance',
  'Animação',
  'Documentário',
  'Mistério',
  'Suspense',
  'Histórico',
  'Biografia',
  'Musical',
  'Guerra',
  'Policial',
  'Western',
  'Esporte',
  'Família',
  'Infantil',
  'Artes Marciais',
  'Super-herói',
  'Thriller',
]